@BaseURL = http://0.0.0.0:5227/api

GET {{BaseURL}}/todo
Authorization: Bearer {{loginRequest.response.body.accessToken}}
Accept: application/json

###

POST {{BaseURL}}/todo
Authorization: Bearer {{loginRequest.response.body.accessToken}}
Content-Type: application/json

{
  "Title": "Cook dinner"
}

###

PUT {{BaseURL}}/todo/1
Authorization: Bearer {{loginRequest.response.body.accessToken}}
Content-Type: application/json

{
  "title": "Do the dishes",
  "isDone": false
}

###

DELETE {{BaseURL}}/todo/3
Authorization: Bearer {{loginRequest.response.body.accessToken}}
Content-Type: application/json

###

POST {{BaseURL}}/register/
Content-Type: application/json

{
  "email": "me2@example.com",
  "password": "P@ssword1"
}

###

# @name loginRequest
POST {{BaseURL}}/login/
Content-Type: application/json

{
  "email": "me2@example.com",
  "password": "P@ssword1"
}